src/Engine/Session.cs
If the commands to be executed on server connection were to throw
any exception, they were being swallowed and not shown in the UI,
so the user could never notice that there was a problem with them
(for example, having a /timeline command to inspect a Twitter user
that doesn't exist, would not yield any visible problem).
=> Engine: bring errors from server.OnConnectCommands to the UI

src/Engine/Session.cs, src/Frontend/CommandManager.cs
Use CreateMessageBuilder() method, instead of its empty constructor,
when the method exists in the class. This is useful in case the class
needs to configure all of its MessageBuilder instances in some way.
=> Engine,Frontend: use CreateMessageBuilder() method when possible

src/Engine-Twitter/Protocols/Twitter/TwitterProtocolManager.cs
When a user mentions you, even if you didn't initiate the conversation,
the tweet appears in this panel too, so it's better to include the
word "Mentions" as well.
=> Engine-Twitter: rename "Replies" chat to "Replies & Mentions"

src/Frontend-GNOME/MainWindow.cs
It's really awkward to have the input box extend all the way to the left below the room/chat tabs. It's more intuitive to have the input right below where your text will display in the chatroom.
This pull request causes the input box to line up with the chat window.
=> Moved input box to be only below chat window/user list

src/Frontend-STFL/Frontend.cs
This ensures that the SSH tunnel, if any, is closed.
=> Frontend-STFL: Call EngineManager.Disconnect() on exit (closes #1034).

src/Frontend-STFL/Frontend.cs, src/Frontend-STFL/Views/ChatView.cs
Make the terminal background color configurable as STFL/Interface/TerminalBackgroundColor and use GetBestTextColor to ensure sufficient contrast.
Implemented when "black on black" turned out not to be very legible.
=> Frontend-STFL: Ensure text color contrast (closes #1033).

src/Frontend-STFL/Views/ChatView.cs
Whenever an ImageMessagePartModel is encountered, output the AlternativeText.
=> Frontend-STFL: Handle image message parts (closes #1035).

Makefile.am
When we're on OS X, some of the libraries we need aren't readily
available from the system. We must therefore set up a fallback path for
the linker to look in mono's library dir, where e.g. libintl lives.
We do this in the script for Smuxi.app already, so let's use the same
paths in the Makefile.
=> build: set libray path for 'run' target on OS X.

src/Engine/Session.cs
This typo was introduced in this commit:
https://github.com/meebey/smuxi/commit/aba9e8f9395c4c6fd879d65d99f373ee0de81ea5
And it was generating an uncaught FormatException due to not
providing the {2}-indexed element.
=> Engine: fix typo in catch block

src/Engine-Twitter/Protocols/Twitter/TwitterProtocolManager.cs, src/Engine/MessageBuffers/SqliteMessageBuffer.cs
Launching a multi-username /timeline command, when using Sqlite
persistence, was giving a ConnectionString initialization error.
The problem was Sqlite handling commas in the same way as semicolons,
so they cannot be used as part of values in the connection string.
The logical way to fix it is replace them with a char that would not
be legal for twitter usernames (so that the timeline for two users
would never collide with the timeline of a user whose username would
be the fomer usernames combined), but that is legal in most filesystems.
=> Engine: fix Sqlite buffer paths when having commas in chat IDs

po-Engine-Campfire/Makefile.in.in, po-Engine-IRC/Makefile.in.in, po-Engine-JabbR/Makefile.in.in, po-Engine-MessageBuffer/Makefile.in.in, po-Engine-Twitter/Makefile.in.in, po-Engine-XMPP/Makefile.in.in, po-Engine/Makefile.in.in, po-Frontend-GNOME-IRC/Makefile.in.in, po-Frontend-GNOME-Twitter/Makefile.in.in, po-Frontend-GNOME-XMPP/Makefile.in.in, po-Frontend-GNOME/Makefile.in.in, po-Frontend/Makefile.in.in, po-Server/Makefile.in.in, po/Makefile.in.in
Fixes build on (at least) Ubuntu 15.04 and later, where modern intltool doesn't
substitute @DATADIRNAME@.
=> Update intltool Makefiles.

.travis.yml
Apparently, we weren't running Frontend-Tests (currently only the nickname completion tests) as part of our continuous integration efforts. Whoops.
=> Travis-CI: also run Frontend-Tests

src/Frontend-STFL/Frontend-STFL.csproj, src/Frontend-STFL/Makefile.am, src/Frontend-STFL/STFL/StflApi.cs, src/Frontend-STFL/STFL/StringOnHeap.cs
Remove code duplication, fix serialization for big-endian systems, work around Mono.Unix.UnixMarshal.PtrToString breakage with UTF-32, fix memory leaks.
=> UTF-32-related fixes to Frontend-STFL

src/Frontend-STFL/STFL/StflApi.cs
When finding the string length, advance by four bytes instead of one.
Sorry for opening a buggy pull request in the first place... now it works.
=> Frontend-STFL: Fix the UTF-32 workaround.

src/Frontend-STFL/Entry.cs
On small terminals, e.g. SSH clients on mobile phones, the screen may not
be wide enough to display more than a few tabs. /window list outputs a list
of all windows and their numbers (for selection via /window number) into
the current chat window.
=> Frontend-STFL: Implement /window list.

src/Engine-Campfire/Protocols/Campfire/CampfireProtocolManager.cs, src/Engine-Campfire/Protocols/Campfire/DTO.cs
The server tells us about the tweets which people paste, so we can use that information to show it, instead of 'unkown action' like we do now.
On the sending side, let the server decide whether we pasted a twitter link or a multi-line paste or whatever. This lets us generate these tweet messages in the channel instead of just pasting the link, and the same goes for multi-line.
=> Campfire: better support for tweets

build/git-contributors
Without this, some contributors would be duplicated, such as:
9 Clement BOURGEOIS
9 Clement Bourgeois
After:
18 Clement Bourgeois
=> build: ignore case in `git-contributors` script

src/Engine-IRC/Protocols/Irc/IrcProtocolManager.cs
Upon successful authentication with the credentials given to the command, `OPER <username> <password>` grants IRC operator (IRCOp) privileges to the issuing user.
Apparently Smuxi didn't support this command yet (without `/quote` or `/raw`).
=> Engine-IRC: implement /oper command

README.md
The launchpad pages for PPAs are the opposite of intuitive when
you just want to know the command to use to subscribe to them,
so as a tiny workaround for smuxi we can add the command here
to prevent extra clicks and headaches.
=> README: add command for daily ppa

src/Engine/Engine.csproj, src/Engine/Makefile.am, src/Engine/MessageBuffers/SqliteMessageBuffer.cs, src/Engine/Messages/Dto/MessageDtoModelV1.cs, src/Engine/Messages/Dto/MessageDtoModelV2.cs
Ability for messages to hold an ID started with a Twitter
feature in [0]. But it was missing serialization, which
was added in [1].
However, SQLiteMessageBuffer serialization was also missing,
something which is fixed in this commit
The consequence of this new property not being present in
MessageBuffer serialization was that the new timeline links
implemented in [0] were only visible in the friends timeline
but not in new timelines spawned by the /timeline command.
[0] https://github.com/meebey/smuxi/commit/e2b6670c7d7e5580aa872944a838e92090f564a5
[1] https://github.com/meebey/smuxi/commit/b19662693f28a14a9f9bc7a74f6d288906eb005a
=> Engine: ID in MessageDTO, for SQLite (de)serialization

src/Engine/Persons/ContactModel.cs
This commented code doesn't have a comment that states its
reason for still existing in the master branch, so it's
better to remove it because it's just noise.
=> Engine: remove some commented code

src/Engine-Tests/MessageBuilderTests.cs
Compare the subparts of the MessageModel first, otherwise this
could fail in a way in which NUnit just compares the .ToString()
result of each, which could be the same and be very confusing.
=> Engine-Tests: improve TestMessage()

src/Engine-Tests/JsonMessageBufferTests.cs, src/Engine-Tests/MessageBufferTestsBase.cs, src/Engine-Tests/SqliteMessageBufferTests.cs
Instead of having the build failing because the
tests throw NotImplementedException, we mark them
as Ignored for the subclasses where they don't
apply. The methods were not implemented because
the interface used for the MessageBuffer chosen
some time ago was IList, but it's too feature-rich
for these backends which, if implemented for them,
would be very expensive operations.
=> Engine-Tests: mark failing NIE tests as Ignored("N/A")

src/Engine-IRC/Protocols/Irc/IrcProtocolManager.cs, src/Engine/Messages/MessageBuilder.cs
In theory, IRC is designed in a way in which all messages from
your current handle are always sent from your own client.
However, with the advent of IRC bridges, such as the Slack one,
it's feasible to use your IRC handle from 2 places: smuxi and
the web (slack UI). In this case, when you sent a message using
the latter, you would get a smuxi highlight on the former
because the engine receives a message that contains your nick,
which is essentially a false positive.
This can be workarounded by adding a comparison to Me's property
in MessageBuilder class just before highlighting.
=> Engine(-IRC): prevent highlights from self (closes: #1095)

build/git-contributors
Without this, some contributors would be duplicated, such as:
27 Clément Bourgeois
16 Clement Bourgeois
After:
43 Clement Bourgeois
Idea borrowed from:
http://stackoverflow.com/a/10207623/544947
=> build: ignore accented chars in `git-contributors` script

src/Engine-Tests/MessageBuilderTests.cs, src/Engine/Config/MessageBuilderSettings.cs, src/Engine/Messages/MessageBuilder.cs
This heuristic should have never considered strings as URLs
if there was not a delimiter character at the end (such as
a space or a question mark or the end of the string).
The testcase that this commit fixes was marked as [Ignore]d,
now it's not disabled anymore.
=> Engine(-Tests): Unbreak heuristic for URLs without protocol (v2)

src/Frontend-GNOME/Makefile.am
The `-D` option is a GNU extension, so trying to build smuxi without GNU coreutils
is not going to work.
Since there's no indication from `./configure` that we need GNU install (as the
first thing it does is check for a BSD-compatible install), let's let it build
with the system's own userland.
---
It might be a bit cleaner to depend on a target that creates the directory, but it's about the same number of changes.
=> Work around BSD install not having -D

Makefile.am
Also rename the previously committed `update-transifex`
to `pull-transifex` to distinguish better and sync with
the tx commands.
I just tested with Mirco that pushing an incomplete
translation to Transifex to a completed translation in
the server does not overwrite the work but it merges
it on the server, so it's fine if no -l parameter is
used here (meaning it defaults to pushing all langs).
--skip is needed because some translations may be
unfinished containing translation files that don't
have any translated strings, and the tx push command
would fail on those with the error "Could not import
file: We're not able to extract any string from the
file uploaded for language Persian (fa) in resource
Smuxi - IRC client: smuxi-server.pot"
=> build: add push-transifex Makefile target

.travis.yml
Trusty is a bit ancient these days (https://twitter.com/directhex/status/1068531931648643074).
At the time of writing this part of the travis YML, there might have not been support for xenial
but now there is: https://docs.travis-ci.com/user/reference/overview/
=> travisCI: from old trusty(14.04) to xenial(16.04)

.travis.yml, configure.ac
Newer versions of Mono such as 6.6.x don't provide NUnit anymore so the
package needs to be installed separately, otherwise the build fails like
it was happening for the master branch in its latest commit:
https://github.com/meebey/smuxi/commit/d4cfb71d70cadd8a9fd218e2089f1e32ad149c63
Whose build log was:
https://travis-ci.org/meebey/smuxi/builds/627714687?utm_source=github_status&utm_medium=notification
=> travis: install libnunit-cil-dev manually to fix build with new Mono

src/Frontend-GNOME/smuxi-frontend-gnome.in
This would be making Smuxi much slower than it needs to; since many optimizations may not be enabled when running in debug mode.
If a developer wants to still run in debug mode after this, she still has two options:
a) Use `make run` which still launches smuxi with the --debug flag.
b) Export env var `MONO_OPTIONS=--debug` before launching smuxi.
=> Frontend-GNOME: remove --debug flag from launcher script
